name: ğŸš€ Deploy website on push

on:
  push:
    branches: main # Triggers only when you push to main

jobs:
  web-deploy:
    name: ğŸ‰ Deploy to cPanel via FTP
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ§° Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: ğŸ“¦ Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: ğŸ“‚ Upload build folder to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_name }}
          password: ${{ secrets.ftp_password }}
          dangerous-clean-slate: true
          local-dir: dist/
          server-dir: github-action.smitbhalani.in/
